### ISSUE TITLE
Searching for ".b2" in Web client shows all files

### ISSUE THREAD

**Issue by ivilata** [ironArray/Caterva2#17]
As of 7269594f, searching for `.b2` in the Web client also shows plain files whose name doesn't contain `.b2`. Thus, one cannot easily restrict entries to just Blosc2 datasets, for instance. I guess this is caused by the subscriber internally storing plain files as Blosc2-compressed frames with the `.b2` extension.

To reproduce, run `python -m caterva2.tests.services`, browse to <http://localhost:8002/>, choose `foo` and enter `.b2` at the search box. The result includes for example `README.md`, whose name doesn't contain `.b2`.

**Comment by martaiborra** [comment]
This has been fixed in the html branch. I will close it when merging into main.

**Comment by ivilata** [comment]
Cool, thanks! :vulcan_salute:
