### ISSUE TITLE
Update reference section

### ISSUE THREAD

**Issue by FrancescAlted** [ironArray/Caterva2#33]
The reference section in docs (https://github.com/Blosc/Caterva2/tree/main/doc/reference) needs to be updated to the new improvements of Caterva2 0.2 (e.g. new [vlmeta](https://github.com/Blosc/Caterva2/blob/main/caterva2/api.py#L229)).

**Comment by ivilata** [comment]
The docs at <https://www.blosc.org/Caterva2/reference/> are up-to-date as well.
