### ISSUE TITLE
Modifying README.md in the publisher does not propagate changes downstream

### ISSUE THREAD

**Issue by FrancescAlted** [ironArray/Caterva2#35]
For example, when modifying `root-example/README.md` the new modifications does not appear when browsing.  The behaviour should be for the publisher to invalidate the cache in subscriber and the subscriber to ask for the new content.

**Comment by ivilata** [comment]
With commit 88e1f1fd, if I run `rm -rf _caterva2 && python -m caterva2.tests.services`, then open `localhost:8002` and click on `foo` then `foo/README.md`, I can see its default content under the "Display" tab (metadata reports 87 bytes). If I then do `echo foo >> _caterva2/data.foo/README.md` (not `root-example/README.md`, as it gets copied during service startup), I see an `UPDATE README.md` message in the publisher log, and if I click again on `foo/README.md`, I can see that the dataset has grown (91 bytes), and I see the changes under "Display".

Could it be that the file that you're modifying is not actually the file being served?

**Comment by ivilata** [comment]
The demo publisher that you tested may have been unresponsive as I can't see any log messages from it after it was started (using `sudo journalctl -u caterva2-publisher@example.service`). I repeated the test that you did on the same machine after restarting the affected publisher service, and it seems to work.

Feel free to close the issue and open a new one if the situation happens again.
