### ISSUE TITLE
Remove root-examples directory

### ISSUE THREAD

**Issue by ivilata** [ironArray/Caterva2#42]
The files in `root-examples` can currently be generated with `python -m caterva2.services.dirroot root-examples` or `caterva2.services.dirroot.create_example_root('root-examples')`. Since they need to be kept in sync along with `SPECS.md`, there is quite a lot of redundancy to keep track of.

The `root-examples` directory may be removed, and tests and docs adapted to use one of the previous methods to get a set of files to work with.

**Comment by FrancescAlted** [comment]
I don't like the idea of have to add code to replicate the `root-examples` directory.  I think using a repo for hosting the data that is going to be there is more straightforward and handier when willing to add any kind of datasets.  With that, I'd close this one.
