### ISSUE TITLE
Add a hash to static caterva2 files

### ISSUE THREAD

**Issue by FrancescAlted** [ironArray/Caterva2#50]
To avoid issues with browser caches, files like [main.js](https://github.com/ironArray/Caterva2/blob/main/caterva2/services/static/main.js) and [main.css](https://github.com/ironArray/Caterva2/blob/main/caterva2/services/static/main.js) should be replaced by versions with e.g. a hash in filename during packaging or during deploy.  For easiness, one should be able to do that easily (e.g. `make hash` or similar).

**Comment by jdavid** [comment]
Done in commit 98ed768aeb3
