### ISSUE TITLE
Respect tab in URL

### ISSUE THREAD

**Issue by FrancescAlted** [ironArray/Caterva2#59]
Now, when going to https://demo.caterva2.net/roots/example/ds-1d-fields.b2nd?roots=example#data and then refreshing the screen, the view changes to https://demo.caterva2.net/roots/example/ds-1d-fields.b2nd?roots=example.  One should keep the `#data` part instead.

**Comment by jdavid** [comment]
Broken again because of a different reason, since custom bootstrap.
