### ISSUE TITLE
Datasets list not showing up without authentication mode

### ISSUE THREAD

**Issue by martaiborra** [ironArray/Caterva2#75]
Right now when launching caterva2 locally without authentication the root list with its datasets is empty (see image).
<img width="1579" alt="Captura de pantalla 2024-09-09 a les 11 33 07" src="https://github.com/user-attachments/assets/32ddac1a-1286-455d-90b9-011c626b19ae">

It seems that the problem may have been caused by 31eb4f9 (since the commit before works as expected).

**Comment by martaiborra** [comment]
To reproduce the problem do:
```
cat2bro
cat2pub foo root-example
cat2sub
```

**Comment by FrancescAlted** [comment]
With latest main that works for me.  Can you try again?

**Comment by FrancescAlted** [comment]
Ups, after removing `_caterva2` the problem still exists.  This is not fixed yet.

**Comment by jdavid** [comment]
The subscriber's default behaviour has change.
Now the subscriber does not connect to the broker, unless told to do so; this can be done in 2 ways:

- Use a `caterva2.toml` configuration file with a `[broker]` section
- Pass the `--broker` option to the subscriber

**Comment by jdavid** [comment]
This is the change:

```
-  parser = utils.get_parser(broker=conf.get('broker.http', 'localhost:8000'),
+  parser = utils.get_parser(broker=conf.get('broker.http', ''),
```

The `caterva2.sample.toml` file works, just copy it to `caterva2.toml`

**Comment by jdavid** [comment]
Update README regarding this in commit 595d5b9d64ae2a138592a8b62fcaa75b3077550f
