### ISSUE TITLE
Adapt caterva2 to the upcoming beta version of python-blosc2

### ISSUE THREAD

**Issue by martaiborra** [ironArray/Caterva2#91]
In the upcoming beta version of python-blosc2, the `cparams` property was added. This property is an instance of the `blosc2.CParams` data class and therefore, the parameters that are not specified are set to the default. On the other hand, caterva2 only stores some cparams in `meta["schunk"]["cparams"]` but not all of them. Caterva2 should be modified so that all the parameters in `blosc2.CParams` are specified in `meta["schunk"]["cparams"]` and then filter the ones that we want to show in the info viewer.

**Comment by FrancescAlted** [comment]
Fixed in #93
